runtime: go115

# app.yaml is supposed to be in the same directory as go.mod.
main: server

# Support using App Engine bundled services (e.g. memcache).
app_engine_apis: true

# Make the app handle index.html so we can check auth. Note that it won't
# actually serve it; this just prevents the static file from being accessed
# directly.
handlers:
- url: /index\.html
  script: auto
  secure: always
- url: /(.*\.(css|eot|html|gif|ico|jpe?g|js|json|png|svg|ttf|txt|woff|woff2))
  static_files: web/\1
  secure: always
  upload: web/.*
- url: /.*
  script: auto
  secure: always
