# TODO: Switch to go112, but doing so apparently requires migrating from
# google.golang.org/appengine to cloud.google.com/go and also makes
# dev_appserver.py unusable. Yay.
# https://cloud.google.com/appengine/docs/standard/go112/go-differences
runtime: go111

# app.yaml is supposed to be in the same directory as go.mod.
main: server

handlers:
- url: /
  static_files: web/index.html
  secure: always
  upload: web/index.html
- url: /(.*\.(css|html|gif|jpe?g|js|png|txt))
  static_files: web/\1
  secure: always
  upload: web/.*
- url: /.*
  script: auto
  secure: always
