# TODO: Switch to go112, but doing so apparently requires migrating from
# google.golang.org/appengine to cloud.google.com/go and also makes
# dev_appserver.py unusable. Yay.
# https://cloud.google.com/appengine/docs/standard/go112/go-differences
runtime: go111

# app.yaml is supposed to be in the same directory as go.mod.
main: server

# Make the app handle index.html so we can check auth.
handlers:
- url: /index\.html
  script: auto
  secure: always
- url: /(.*\.(css|eot|html|gif|ico|jpe?g|js|json|png|svg|ttf|txt|woff|woff2))
  static_files: web/\1
  secure: always
  upload: web/.*
- url: /.*
  script: auto
  secure: always
