# TODO: Switch to go112, but doing so apparently requires migrating from
# google.golang.org/appengine to cloud.google.com/go and also makes
# dev_appserver.py unusable. Yay.
# https://cloud.google.com/appengine/docs/standard/go112/go-differences
runtime: go111

# TODO: This causes an error:
# ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: script field for handler
# '/_ah/remote_api(/.*)?' must be set to 'auto' for runtime go112.
#builtins:
#- remote_api: on

handlers:
- url: /index\.html
  script: auto
  secure: always
- url: /(.*\.(css|html|gif|jpe?g|js|png|txt))
  static_files: static/\1
  secure: always
  upload: static/.*
- url: /.*
  script: auto
  secure: always
