application: nup
version: 1
runtime: go
api_version: go1

builtins:
- remote_api: on

handlers:
- url: /index\.html
  script: _go_app
  secure: always
- url: /(.*\.(css|html|js|png))
  static_files: static/\1
  secure: always
  upload: static/.*
- url: /.*
  script: _go_app
  secure: always
